spring.banner.location=banner.txt
spring.jpa.open-in-view=false
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.platform=mysql
spring.datasource.url=jdbc:mysql://15.206.24.39:3306/dual_vet
spring.datasource.username=jogendra_k
spring.datasource.password=Dev@1234
spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
spring.application.name=DualVet
logging.file.name=dualvet.log
#management.tracing.sampling.probability=1.0
#logging.level.root=WARN
#logging.level.org.springframework=ERROR
#logging.level.com.dualvet=DEBUG
logging.level.com.strive.logs=INFO
logging.pattern.console=TEST | %d{yyyy-MM-dd HH:mm:ss} | %-5level | %logger{36} | %msg%n




# ----------- Company Google Credentials -------------------------
spring.security.oauth2.client.registration.google.client-id=36345470060-gddbf9qdrmdlintdi59i7q580k7voom1.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=daU8Ibak0UI12x3nA9fR1YDX
