
export const itiHistoryData = (data) => {
    return data.map(formData => [
      formData.id,
      `"${formData.itiName}"`,
      //`"${formData.address}"`, // Wrap address in quotes to handle commas
      //`"${formData.principalAndVicePrincipal}"`,
      //`"${formData.principalContactNumber}"`,
      //`"${formData.itiEmailId}"`,
      `"${formData.instructorName}"`,
      `"${formData.instructorEmailId}"`,
      `"${formData.instructorContactNumber}"`,
      `"${formData.itiTrade}"`,
      `"${formData.noOfTrainees}"`,
      `"${formData.noOfSeatsAvailable}"`,
      `"${formData.courseDurationYear}"`,
      `"${formData.employmentType}"`,
      `"${formData.state}"`,
     `"${formData.district}"`,
      formData.createdBy,
      formData.createdOn,
      formData.updatedBy,
      formData.updatedOn,
      `"${formData.remarks}"`,
      `"${formData.status}"`,
    ]);
  };

  export const industryhistoryData = (data) => {
  return data.map(formData => [
    formData.id,
    `"${formData.industryName}"`,
    `"${formData.contactName}"`,
    `"${formData.contactNumber}"`,
    `"${formData.emailId}"`,
    `"${formData.nearestCity}"`,
    `"${formData.district}"`,
    formData.state,
    formData.pincode,
    `"${formData.lat}"`,
    `"${formData.lan}"`,
    `"${formData.designationOfSpoc}"`,
    formData.sizeOfIndustry,
    formData.sector,
    //formData.domain,
    formData.academicYear,
    `"${formData.trade}"`,
    formData.ojtSupport,
    formData.noOfOjtTrainees,
    formData.apprenticeshipSupport,
    formData.noOfApprenticeship,
    formData.placementsSupport,
    formData.noOfPlacements,
    formData.isStipendProvided,
    formData.isFoodProvided,
    formData.isTransportProvided,
    formData.isAccommodationProvided,
    formData.isMouSign,
    formData.createdBy,
    formData.createdOn,
    formData.updatedBy,
    formData.updatedOn,
    `"${formData.remarks}"`,
    `"${formData.status}"`,
  ])};
   export const ipthistorydownloadData = (data) => {
   return data.map(formData => [
    formData.id,
    `"${formData.traineesName}"`,
    formData.traineesCollegeRegId,
    `"${formData.traineesItiTrade}"`,
    `"${formData.phoneNumber}"`,
    `"${formData.emailId}"`,
    formData.stipend,
    `"${formData.itiName}"`,
    `"${formData.instructorName}"`,
    formData.iptYear,
    `"${formData.industryName}"`,
    formData.insuranceStatus,
    formData.ppeKitStatus,
    formData.iptStart,
    formData.iptEnd,
    `"${formData.employmentType}"`,
    formData.iptDiaryProvided,
    formData.createdBy,
    formData.createdOn,
    formData.updatedBy,
    formData.updatedOn,
    `"${formData.remarks}"`,
    `"${formData.status}"`,
    formData.academicYear
  ])};